language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t asad-mallick/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true asad-mallick/docker-react npm run test
